---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.4.2
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

We need to execute the *ipython* magic twice.  We do not know why.  Once is not enough.  If you add a comment before the *ipython* magic, even twice is not enough.

```{python}
from scipy import *
import numpy as np
from numpy.random import rand, uniform
import matplotlib.pyplot as plt
import matplotlib.animation
import PlanktonSignaling.basics as PS
import PlanktonSignaling.BlobDetection as BD
import PlanktonSignaling.Deposition as DP
import profile
import time

# %matplotlib notebook
# %matplotlib notebook
```

Note here that $d_1 = \frac{\kappa \lambda_0}{v^2}$ and $d_2 = \frac{\beta}{\lambda_0}$. For the correct deposition functions, use linAtanDep2 and atanDep2 to include tanh.

```{python}
particleMeshsize = 40
meshsize = 120
numb = 120**2 #must be a perfect square.
LL = 10
Swimmers = PS.Plankton(DP.atanDep2,N = meshsize,depMaxStr=.01,Const=3,L=LL,k=0.02,epsilon=1e-3,speed=1,
             lambda0=1,kappa=.2,beta=5,depThreshold=0.05, depTransWidth=0.03, dens=6.476363593662468, num = numb)

def initial_conditions(x,y):
    return(0*x+0.012)

print(Swimmers.d1)
print(Swimmers.d2)
```

```{python}
def particleProjection(pos,meshsize):
    
    x = r_[0:Swimmers.L:1j*meshsize]# setup the spatial mesh. It is a long row vector

    # Create some local coordinates for the square domain.
    y = 1*x
    xm,ym = np.meshgrid(x,y)

    f = zeros((meshsize,meshsize))
    Std = (Swimmers.L/(meshsize-1))**2
    
    boundaryCutoff = 32*Std

    for i in range(0,Swimmers.num):
        A, B, C, D = 0,0,0,0
        
        p = pos[i,:]
        
        f = f + (1/(4*pi*Std))*exp(-((xm-p[0])**2+(ym-p[1])**2)/4/Std)
        
        if ((p[0])**2<boundaryCutoff):
            f = f + (1/(4*pi*Std))*exp(-((xm-p[0]-Swimmers.L)**2+(ym-p[1])**2)/4/Std)
            A = 1
        if ((p[0]-Swimmers.L)**2<boundaryCutoff):
            f = f + (1/(4*pi*Std))*exp(-((xm-p[0]+Swimmers.L)**2+(ym-p[1])**2)/4/Std)
            B = 1
        if ((p[1])**2<boundaryCutoff):
            f = f + (1/(4*pi*Std))*exp(-((xm-p[0])**2+(ym-p[1]-Swimmers.L)**2)/4/Std)
            C = 1
        if ((p[1]-Swimmers.L)**2<boundaryCutoff):
            f = f + (1/(4*pi*Std))*exp(-((xm-p[0])**2+(ym-p[1]+Swimmers.L)**2)/4/Std)
            D = 1
            
        if ((A == 1) and (C == 1)): #Plankton in Lower Left Corner
            f = f + (1/(4*pi*Std))*exp(-((xm-p[0]-Swimmers.L)**2+(ym-p[1]-Swimmers.L)**2)/4/Std)
        if ((A == 1) and (D == 1)): #Plankton in Upper Left Corner
            f = f + (1/(4*pi*Std))*exp(-((xm-p[0]-Swimmers.L)**2+(ym-p[1]+Swimmers.L)**2)/4/Std)
        if ((B == 1) and (C == 1)): #Plankton in Lower Right Corner
            f = f + (1/(4*pi*Std))*exp(-((xm-p[0]+Swimmers.L)**2+(ym-p[1]-Swimmers.L)**2)/4/Std)
        if ((B == 1) and (D == 1)): #Plankton in Upper Right Corner
            f = f + (1/(4*pi*Std))*exp(-((xm-p[0]+Swimmers.L)**2+(ym-p[1]+Swimmers.L)**2)/4/Std)
            
    return xm,ym,f*(Swimmers.density*Swimmers.L**2/Swimmers.num)
```

```{python}
def particleProjectionFaster(pos,meshsize):
    
    x = r_[0:Swimmers.L:1j*meshsize]# setup the spatial mesh. It is a long row vector

    # Create some local coordinates for the square domain.
    y = 1*x
    xm,ym = np.meshgrid(x,y)

    f = zeros((meshsize,meshsize))
    Std = (Swimmers.L/(meshsize-1))**2

    
    boundaryCutoff = 32*Std
    
    intDelta = int((meshsize-1)*8*sqrt(Std)/Swimmers.L)
    
    for i in range(0,Swimmers.num):

        A, B, C, D = 0,0,0,0

        p = pos[i,:]
        
        centerX = int((meshsize-1)*p[0]/Swimmers.L)
        centerY = int((meshsize-1)*p[1]/Swimmers.L)
        
        lowerX      = max(0,centerX-intDelta)
        lowerXplus  = max(0,centerX-intDelta + (meshsize-1))
        lowerXminus = max(0,centerX-intDelta - (meshsize-1))
        upperX      = min(meshsize,centerX+intDelta)
        upperXplus  = min(meshsize,centerX+intDelta + (meshsize-1))
        upperXminus = min(meshsize,centerX+intDelta - (meshsize-1))

        lowerY      = max(0,centerY-intDelta)
        lowerYplus  = max(0,centerY-intDelta + (meshsize-1))
        lowerYminus = max(0,centerY-intDelta - (meshsize-1))
        upperY      = min(meshsize,centerY+intDelta)
        upperYplus  = min(meshsize,centerY+intDelta + (meshsize-1))
        upperYminus = min(meshsize,centerY+intDelta - (meshsize-1))
        
        sliceX = slice(lowerX,upperX)
        sliceY = slice(lowerY,upperY)
        
        f[sliceY,sliceX] = f[sliceY,sliceX] + (1/(4*pi*Std))*exp(-((xm[sliceY,sliceX]-p[0])**2+(ym[sliceY,sliceX]-p[1])**2)/4/Std)
        if ((p[0])**2<boundaryCutoff):
            sliceX = slice(lowerXplus,upperXplus)
            sliceY = slice(lowerY,upperY)
            f[sliceY,sliceX] = f[sliceY,sliceX] + (1/(4*pi*Std))*exp(-((xm[sliceY,sliceX]-p[0]-Swimmers.L)**2+(ym[sliceY,sliceX]-p[1])**2)/4/Std)
            A = 1
        if ((p[0]-Swimmers.L)**2<boundaryCutoff):
            sliceX = slice(lowerXminus,upperXminus)
            sliceY = slice(lowerY,upperY)
            f[sliceY,sliceX] = f[sliceY,sliceX] + (1/(4*pi*Std))*exp(-((xm[sliceY,sliceX]-p[0]+Swimmers.L)**2+(ym[sliceY,sliceX]-p[1])**2)/4/Std)
            B = 1
        if ((p[1])**2<boundaryCutoff):
            sliceX = slice(lowerX,upperX)
            sliceY = slice(lowerYplus,upperYplus)
            f[sliceY,sliceX] = f[sliceY,sliceX] + (1/(4*pi*Std))*exp(-((xm[sliceY,sliceX]-p[0])**2+(ym[sliceY,sliceX]-p[1]-Swimmers.L)**2)/4/Std)
            C = 1
        if ((p[1]-Swimmers.L)**2<boundaryCutoff):
            sliceX = slice(lowerX,upperX)
            sliceY = slice(lowerYminus,upperYminus)
            f[sliceY,sliceX] = f[sliceY,sliceX] + (1/(4*pi*Std))*exp(-((xm[sliceY,sliceX]-p[0])**2+(ym[sliceY,sliceX]-p[1]+Swimmers.L)**2)/4/Std)
            D = 1
        if (A == 1 and C == 1): #Plankton in Lower Left Corner
            sliceX = slice(lowerXplus,upperXplus)
            sliceY = slice(lowerYplus,upperYplus)
            f[sliceY,sliceX] = f[sliceY,sliceX] + (1/(4*pi*Std))*exp(-((xm[sliceY,sliceX]-p[0]-Swimmers.L)**2+(ym[sliceY,sliceX]-p[1]-Swimmers.L)**2)/4/Std)
        if (A == 1 and D == 1): #Plankton in Lower Left Corner
            sliceX = slice(lowerXplus,upperXplus)
            sliceY = slice(lowerYminus,upperYminus)
            f[sliceY,sliceX] = f[sliceY,sliceX] + (1/(4*pi*Std))*exp(-((xm[sliceY,sliceX]-p[0]-Swimmers.L)**2+(ym[sliceY,sliceX]-p[1]+Swimmers.L)**2)/4/Std)
        if (B == 1 and C == 1): #Plankton in Upper Right Corner
            sliceX = slice(lowerXminus,upperXminus)
            sliceY = slice(lowerYplus,upperYplus)
            f[sliceY,sliceX] = f[sliceY,sliceX] + (1/(4*pi*Std))*exp(-((xm[sliceY,sliceX]-p[0]+Swimmers.L)**2+(ym[sliceY,sliceX]-p[1]-Swimmers.L)**2)/4/Std)
        if (B == 1 and D == 1): #Plankton in Lower Right Corner
            sliceX = slice(lowerXminus,upperXminus)
            sliceY = slice(lowerYminus,upperYminus)
            f[sliceY,sliceX] = f[sliceY,sliceX] + (1/(4*pi*Std))*exp(-((xm[sliceY,sliceX]-p[0]+Swimmers.L)**2+(ym[sliceY,sliceX]-p[1]+Swimmers.L)**2)/4/Std)
    return xm,ym,f*(Swimmers.density*Swimmers.L**2/Swimmers.num)
```

```{python}
Swimmers.SetIC(initial_conditions)

#Fixed the initialization
pos = np.empty((1,2))

aggreg = [array([0,0])]
areaAve = [array([0,0])]
lenn= int(sqrt(numb))
th = rand()*2*pi
vel = [array([cos(th),sin(th)])]

for l in range(0,lenn):
    for k in range(0,lenn):
        pos = np.append(pos,[array([mod(k*(Swimmers.L*1/lenn) + 0.01*(rand()-0.5) + 0.5*(Swimmers.L*1/lenn),Swimmers.L),
                                  mod(l*(Swimmers.L*1/lenn) + 0.01*(rand()-0.5) + 0.5*(Swimmers.L*1/lenn),Swimmers.L)])],axis=0)
        th  = rand()*2*pi
        vel = np.append(vel,[array([cos(th),sin(th)])],axis=0)
        
plt.figure()
plt.pcolormesh(Swimmers.xm,Swimmers.ym,Swimmers.Meshed())
plt.plot(pos[:,0],pos[:,1],'r.',MarkerSize=.5)
plt.colorbar()
plt.show()
```

```{python}
Swimmers.SetIC(initial_conditions)

simTime = 100

pos_store = list([pos[:,:]])
pos_store = list([np.array(pos)])


scalar_store = list([Swimmers.Meshed()])

count = 1
for plot in range(0,1):
    for k in range(0,simTime):
        Swimmers.UpdateSlice(Swimmers.scalar,pos,vel)
        pos_store.append(np.array(pos))
        scalar_store.append(Swimmers.Meshed())
```

### Comparison between Slicing and Regular Update Methods: Time

```{python}
#First, we use the regular method
Swimmers.SetIC(initial_conditions)

#Fixed the initialization here
pos = np.empty((1,2))

lenn= int(sqrt(numb))
th = rand()*2*pi
vel = [array([cos(th),sin(th)])]

for l in range(0,lenn):
    for k in range(0,lenn):
        pos = np.append(pos,[array([mod(k*(Swimmers.L*1/lenn) + 0.01*(rand()-0.5) + 0.5*(Swimmers.L*1/lenn),Swimmers.L),
                                  mod(l*(Swimmers.L*1/lenn) + 0.01*(rand()-0.5) + 0.5*(Swimmers.L*1/lenn),Swimmers.L)])],axis=0)
        th  = rand()*2*pi
        vel = np.append(vel,[array([cos(th),sin(th)])],axis=0)

simTime = 100

pos2 = pos
pos_store = list([pos[:,:]])
pos_store = list([np.array(pos)])

pos_storeinit = list([pos[:,:]])
pos_storeinit = list([np.array(pos)])
velinit = vel

scalar_store = list([Swimmers.Meshed()])
start = time.process_time()

for plot in range(0,1):
    for k in range(0,simTime):
        Swimmers.Update(Swimmers.scalar,pos,vel)
        pos_store.append(np.array(pos))
        scalar_store.append(Swimmers.Meshed())
print('Regular Update Time: ',time.process_time()-start)

#Trying with UpdateSlice to see difference 

Swimmers.SetIC(initial_conditions)

#Fixed the initialization
start = time.process_time()

pos_store2 = list([pos2[:,:]])
pos_store2 = list([np.array(pos2)])
vel2 = velinit

scalar_store2 = list([Swimmers.Meshed()])

start = time.process_time()
for plot in range(0,1):
    for k in range(0,simTime):
        Swimmers.UpdateSlice(Swimmers.scalar,pos,vel)
        pos_store2.append(np.array(pos))
        scalar_store2.append(Swimmers.Meshed())
print('Slicing Update Time: ',time.process_time()-start)
```

### Comparison between Regular and Slicing Update Methods: Error

```{python}
#First, we use the regular method
Swimmers.SetIC(initial_conditions)

#Fixed the initialization here
pos = np.empty((1,2))

lenn= int(sqrt(numb))
th = rand()*2*pi
vel = [array([cos(th),sin(th)])]

for l in range(0,lenn):
    for k in range(0,lenn):
        pos = np.append(pos,[array([mod(k*(Swimmers.L*1/lenn) + 0.01*(rand()-0.5) + 0.5*(Swimmers.L*1/lenn),Swimmers.L),
                                  mod(l*(Swimmers.L*1/lenn) + 0.01*(rand()-0.5) + 0.5*(Swimmers.L*1/lenn),Swimmers.L)])],axis=0)
        th  = rand()*2*pi
        vel = np.append(vel,[array([cos(th),sin(th)])],axis=0)

pos2 = pos
pos_store = list([pos[:,:]])
pos_store = list([np.array(pos)])

pos_storeinit = list([pos[:,:]])
pos_storeinit = list([np.array(pos)])
velinit = vel

scalar_store = list([Swimmers.Meshed()])

Swimmers.Update(Swimmers.scalar,pos,vel)
pos_store.append(np.array(pos))
scalar_store.append(Swimmers.Meshed())

#Trying with UpdateSlice to see difference 

Swimmers.SetIC(initial_conditions)

#Fixed the initialization

pos_store2 = list([pos2[:,:]])
pos_store2 = list([np.array(pos2)])
vel2 = velinit
scalar_store2 = list([Swimmers.Meshed()])

Swimmers.UpdateSlice(Swimmers.scalar,pos2,vel2)
pos_store2.append(np.array(pos2))
scalar_store2.append(Swimmers.Meshed())

print('Relative Error: {0}'.format((sum(scalar_store2[1]) - sum(scalar_store[1]))/(sum(scalar_store[1]))))
```

### Comparison of methods with contour smoothing

```{python}
start = time.process_time()
ContoursAll = np.zeros((len(pos_store),particleMeshsize,particleMeshsize))
for k in range(0,len(scalar_store)):
    xm, ym, ContoursAll[k,:,:] = particleProjection(pos_store[k],particleMeshsize)
#np.save('Contours', ContoursAll)
print('Time: ',time.process_time()-start)
```

```{python}
start = time.process_time()
ContoursAll2 = np.zeros((len(pos_store),particleMeshsize,particleMeshsize))
for k in range(0,len(scalar_store)):
    xm, ym, ContoursAll2[k,:,:] = particleProjectionFaster(pos_store[k],particleMeshsize)
#np.save('Contours', ContoursAll)
print('Time: ',time.process_time()-start)
print('Rel err: ',amax(abs(ContoursAll[0,:,:]-ContoursAll2[0,:,:]))/amax(abs(ContoursAll[0,:,:])))
```

### Snapshot of initial plankton density

```{python}
pos = pos_store[0]
plt.figure()
plt.pcolormesh(xm,ym,ContoursAll[0,:,:])
plt.plot(pos[:,0],pos[:,1],'ro',MarkerSize=.75)
plt.colorbar()
#plt.clim([6,7])
plt.show()
```

### Difference between total chemical over time

```{python}
plt.figure()
Chem1 = []
Chem2 = []
for k in range(0,simTime):
    Chem1 = np.append(Chem1,sum(scalar_store[k]))
    Chem2 = np.append(Chem2,sum(scalar_store2[k]))
plt.plot(linspace(0,simTime,simTime),Chem1, 'r-')
plt.plot(linspace(0,simTime,simTime),Chem2, 'b-')
```

# Animations


### Basic Animation with Chemical and Plankton Combined

```{python}
fig   = plt.figure()
ax    = plt.subplot(1,1,1)
field = ax.pcolormesh(Swimmers.xm,Swimmers.ym,scalar_store2[0])
field.set_clim(0,0.03)
dots, = ax.plot([], [], 'r.',MarkerSize=.55)
fig.colorbar(field)

plt.suptitle(r'$d_1 = {0},d_2={1}$'.format(Swimmers.d1, Swimmers.d2), fontsize = 10)

def initit():
    dots.set_data([], [])
    return field,dots

def animate(k):
    arr = scalar_store[k]
    arr = arr[:-1, :-1]
    field.set_array(arr.ravel())
    plt.title(r'Time = ${0}$'.format(k*Swimmers.k), fontsize = 20)
    dots.set_data(pos_store2[k][:,0],pos_store2[k][:,1])

    return dots,field
    
anim = matplotlib.animation.FuncAnimation(fig,animate,frames=range(0,simTime,2),
                                          interval=50,blit=False,repeat=False)

# Uncomment if you want to save it to a file.  Requires mencoder or ffmpeg or some writer utility to generate the file.
#anim.save('d102_d5_delta1e3_Atandep_HighDensity_scalingsmall3.mp4', writer='ffmpeg')
plt.show()
```

### Animation for Plankton Aggregation Contours

```{python}
fig  = plt.figure()
field1 = plt.pcolormesh(xm,ym,ContoursAll[0,:,:])
fig.colorbar(field1)

def initit():
    
    return field1

def animate(k):
    arr2 = ContoursAll[k,:,:]
    arr2 = arr2[:-1,:-1]
    field1.set_array(arr2.ravel())
    plt.suptitle(r'$d_1 = {0},d_2={1}$, Time = ${2}$'.format(Swimmers.d1, Swimmers.d2,round(k*Swimmers.k,2)), fontsize = 20)
    return field1,
    
anim = matplotlib.animation.FuncAnimation(fig,animate,frames=range(0,30,1),
                                          interval=80,blit=False,repeat=False)

# Uncomment if you want to save it to a file.  Requires mencoder or ffmpeg or some writer utility to generate the file.
#anim.save('d102_d5_delta1e3_Atandep_Contours.mp4', writer='ffmpeg')
plt.show()
```

### Animation for finding the most unstable wave numbers using a 2D Fast Fourier Transform

```{python}
fig   = plt.figure()
cmap = plt.get_cmap('binary')
freq = (len(Swimmers.xm)*2*pi/(Swimmers.L))*fftfreq(len(Swimmers.xm))
ax    = plt.subplot(1,1,1)
omega = np.fft.fft2(scalar_store[0])
field = ax.pcolormesh(np.fft.fftshift(freq),np.fft.fftshift(freq),log(abs(np.fft.fftshift(omega))),cmap=cmap)
flat=log(abs(fftshift(omega))).flatten()
flat.sort()
field.set_clim(flat[-2]-.1,flat[-2])
ax.set_ylim(-10,10)
ax.set_xlim(-10,10)
def xy(r,phi):
    return r*np.cos(phi), r*np.sin(phi)

phis=np.arange(0,6.28,0.01)

#Input the norm of the most unstable wave number using the stability code
r = 5.44
ax.plot( *xy(r,phis), c='r',ls='-' )

fig.colorbar(field)

plt.suptitle(r'$d_1 = {0},d_2={1}$'.format(Swimmers.d1, Swimmers.d2), fontsize = 10)

def initit():
    return field

def animate(k):
    omega = fft2(scalar_store[k])
    arr = log(abs(fftshift(omega)))
    arr = arr[:-1, :-1]
    field.set_array(arr.ravel())
    flat=log(abs(fftshift(omega))).flatten()
    flat.sort()
    field.set_clim(flat[-2]-.21,flat[-2])
    plt.title(r'T = {0}'.format(round(k*Swimmers.k,2)), fontsize = 15)
    
    return field
    
anim = matplotlib.animation.FuncAnimation(fig,animate,frames=range(0,len(scalar_store),1),
                                          interval=200,blit=False,repeat=False)

# Uncomment if you want to save it to a file.  Requires mencoder or ffmpeg or some writer utility to generate the file.
#anim.save('High_Wave_NumberAnim_d102_d250_Slow.mp4', writer='ffmpeg')
plt.show()
```
